name: Mock Github actions workflow
run-name: Mock Github actions for ${{ github.actor }}
on: [push]
jobs:
  Pretend-to-do-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Where are we
        run: pwd && ls && echo ${{ github.workspace }}
      - name: Publish Gradle Project
        working-directory: mock_gradle_proj
        run: gradle publish
      - name: Pacakge Maven Project
        working-directory: mock_maven_proj
        run: mvn package
