name: Mock Github actions workflow
run-name: Mock Github actions for ${{ github.actor }}
on: [push]
jobs:
  Pretend-to-do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish Gradle Project
        working-directory: mock_gradle_proj
        run: gradle publish
      - name: Package Maven Project
        working-directory: mock_maven_proj
        run: mvn package
      - name: Build Docker
        working-directory: mock_docker_proj
        run: docker build -t mock_proj
      - name: Push Docker
        working-directory: mock_docker_proj
        run: docker push mock_proj
